//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObrasAvalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObrasAvalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracion.
        /// </summary>
        public static string MenuAdministracion {
            get {
                return ResourceManager.GetString("MenuAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string MenuClientes {
            get {
                return ResourceManager.GetString("MenuClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string MenuEmpresa {
            get {
                return ResourceManager.GetString("MenuEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion.
        /// </summary>
        public static string MenuEntidadesGestion {
            get {
                return ResourceManager.GetString("MenuEntidadesGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de Materiales.
        /// </summary>
        public static string MenuGestionDeMateriales {
            get {
                return ResourceManager.GetString("MenuGestionDeMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuIdioma {
            get {
                return ResourceManager.GetString("MenuIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string MenuProyectos {
            get {
                return ResourceManager.GetString("MenuProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string SubMenuAbrir {
            get {
                return ResourceManager.GetString("SubMenuAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acopios.
        /// </summary>
        public static string SubMenuAcopios {
            get {
                return ResourceManager.GetString("SubMenuAcopios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string SubMenuAdministrador {
            get {
                return ResourceManager.GetString("SubMenuAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador de Materiales.
        /// </summary>
        public static string SubMenuAdministradorDeMateriales {
            get {
                return ResourceManager.GetString("SubMenuAdministradorDeMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string SubMenuAgregar {
            get {
                return ResourceManager.GetString("SubMenuAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Factura.
        /// </summary>
        public static string SubMenuAgregarFactura {
            get {
                return ResourceManager.GetString("SubMenuAgregarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Remito.
        /// </summary>
        public static string SubMenuAgregarRemito {
            get {
                return ResourceManager.GetString("SubMenuAgregarRemito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aportes.
        /// </summary>
        public static string SubMenuAportes {
            get {
                return ResourceManager.GetString("SubMenuAportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avance de Obra.
        /// </summary>
        public static string SubMenuAvanceDeObra {
            get {
                return ResourceManager.GetString("SubMenuAvanceDeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvanceMensual.
        /// </summary>
        public static string SubMenuAvanceMensual {
            get {
                return ResourceManager.GetString("SubMenuAvanceMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja.
        /// </summary>
        public static string SubMenuCaja {
            get {
                return ResourceManager.GetString("SubMenuCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartera de Cheques.
        /// </summary>
        public static string SubMenuCarteraDeCheques {
            get {
                return ResourceManager.GetString("SubMenuCarteraDeCheques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        public static string SubMenuCashFlow {
            get {
                return ResourceManager.GetString("SubMenuCashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string SubMenuCerrar {
            get {
                return ResourceManager.GetString("SubMenuCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string SubMenuCertificados {
            get {
                return ResourceManager.GetString("SubMenuCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheques/Extracciones.
        /// </summary>
        public static string SubMenuCheques_Extracciones {
            get {
                return ResourceManager.GetString("SubMenuCheques/Extracciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string SubMenuClientes {
            get {
                return ResourceManager.GetString("SubMenuClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobranzas.
        /// </summary>
        public static string SubMenuCobranzas {
            get {
                return ResourceManager.GetString("SubMenuCobranzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra de Moneda Extranjera.
        /// </summary>
        public static string SubMenuCompraDeMonedaExtranjera {
            get {
                return ResourceManager.GetString("SubMenuCompraDeMonedaExtranjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        public static string SubMenuComprar {
            get {
                return ResourceManager.GetString("SubMenuComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        public static string SubMenuCompras {
            get {
                return ResourceManager.GetString("SubMenuCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumos.
        /// </summary>
        public static string SubMenuConsumos {
            get {
                return ResourceManager.GetString("SubMenuConsumos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de Gestion.
        /// </summary>
        public static string SubMenuControlDeGestion {
            get {
                return ResourceManager.GetString("SubMenuControlDeGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costos Indirectos.
        /// </summary>
        public static string SubMenuCostosIndirectos {
            get {
                return ResourceManager.GetString("SubMenuCostosIndirectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizaciones.
        /// </summary>
        public static string SubMenuCotizaciones {
            get {
                return ResourceManager.GetString("SubMenuCotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string SubMenuCuenta {
            get {
                return ResourceManager.GetString("SubMenuCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitos Internos.
        /// </summary>
        public static string SubMenuDebitosInternos {
            get {
                return ResourceManager.GetString("SubMenuDebitosInternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitos Varios.
        /// </summary>
        public static string SubMenuDebitosVarios {
            get {
                return ResourceManager.GetString("SubMenuDebitosVarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depositar.
        /// </summary>
        public static string SubMenuDepositar {
            get {
                return ResourceManager.GetString("SubMenuDepositar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depositos.
        /// </summary>
        public static string SubMenuDepositos {
            get {
                return ResourceManager.GetString("SubMenuDepositos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Proveedores.
        /// </summary>
        public static string SubMenuDeProveedores {
            get {
                return ResourceManager.GetString("SubMenuDeProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economia.
        /// </summary>
        public static string SubMenuEconomia {
            get {
                return ResourceManager.GetString("SubMenuEconomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economico.
        /// </summary>
        public static string SubMenuEconomico {
            get {
                return ResourceManager.GetString("SubMenuEconomico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo.
        /// </summary>
        public static string SubMenuEfectivo {
            get {
                return ResourceManager.GetString("SubMenuEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Cheque.
        /// </summary>
        public static string SubMenuEmitirCheque {
            get {
                return ResourceManager.GetString("SubMenuEmitirCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Factura.
        /// </summary>
        public static string SubMenuEmitirFactura {
            get {
                return ResourceManager.GetString("SubMenuEmitirFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Recibo.
        /// </summary>
        public static string SubMenuEmitirRecibo {
            get {
                return ResourceManager.GetString("SubMenuEmitirRecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir Transferencia.
        /// </summary>
        public static string SubMenuEmitirTransferencia {
            get {
                return ResourceManager.GetString("SubMenuEmitirTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades Financieras.
        /// </summary>
        public static string SubMenuEntidadesFinancieras {
            get {
                return ResourceManager.GetString("SubMenuEntidadesFinancieras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SubMenuEspañol {
            get {
                return ResourceManager.GetString("SubMenuEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturacion.
        /// </summary>
        public static string SubMenuFacturacion {
            get {
                return ResourceManager.GetString("SubMenuFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        public static string SubMenuFacturas {
            get {
                return ResourceManager.GetString("SubMenuFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fideicomisos de Moneda Extranjera.
        /// </summary>
        public static string SubMenuFideicomisosDeMonedaExtranjera {
            get {
                return ResourceManager.GetString("SubMenuFideicomisosDeMonedaExtranjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financiero.
        /// </summary>
        public static string SubMenuFinanciero {
            get {
                return ResourceManager.GetString("SubMenuFinanciero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos Generales.
        /// </summary>
        public static string SubMenuGastosGenerales {
            get {
                return ResourceManager.GetString("SubMenuGastosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SubMenuGeneral {
            get {
                return ResourceManager.GetString("SubMenuGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion.
        /// </summary>
        public static string SubMenuGestion {
            get {
                return ResourceManager.GetString("SubMenuGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuestos.
        /// </summary>
        public static string SubMenuImpuestos {
            get {
                return ResourceManager.GetString("SubMenuImpuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes.
        /// </summary>
        public static string SubMenuInformes {
            get {
                return ResourceManager.GetString("SubMenuInformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes Anuales.
        /// </summary>
        public static string SubMenuInformesAnuales {
            get {
                return ResourceManager.GetString("SubMenuInformesAnuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SubMenuIngles {
            get {
                return ResourceManager.GetString("SubMenuIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos Brutos.
        /// </summary>
        public static string SubMenuIngresosBrutos {
            get {
                return ResourceManager.GetString("SubMenuIngresosBrutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos y Egresos por Obra.
        /// </summary>
        public static string SubMenuIngresosYEgresosPorObra {
            get {
                return ResourceManager.GetString("SubMenuIngresosYEgresosPorObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internos.
        /// </summary>
        public static string SubMenuInternos {
            get {
                return ResourceManager.GetString("SubMenuInternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva.
        /// </summary>
        public static string SubMenuIva {
            get {
                return ResourceManager.GetString("SubMenuIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string SubMenuListar {
            get {
                return ResourceManager.GetString("SubMenuListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Cheques.
        /// </summary>
        public static string SubMenuListarCheques {
            get {
                return ResourceManager.GetString("SubMenuListarCheques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Compras.
        /// </summary>
        public static string SubMenuListarCompras {
            get {
                return ResourceManager.GetString("SubMenuListarCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Depositos.
        /// </summary>
        public static string SubMenuListarDepositos {
            get {
                return ResourceManager.GetString("SubMenuListarDepositos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Facturas.
        /// </summary>
        public static string SubMenuListarFacturas {
            get {
                return ResourceManager.GetString("SubMenuListarFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Recibos.
        /// </summary>
        public static string SubMenuListarRecibos {
            get {
                return ResourceManager.GetString("SubMenuListarRecibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Transferencias.
        /// </summary>
        public static string SubMenuListarTransferencias {
            get {
                return ResourceManager.GetString("SubMenuListarTransferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Ventas.
        /// </summary>
        public static string SubMenuListarVentas {
            get {
                return ResourceManager.GetString("SubMenuListarVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano de Obra.
        /// </summary>
        public static string SubMenuManoDeObra {
            get {
                return ResourceManager.GetString("SubMenuManoDeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales.
        /// </summary>
        public static string SubMenuMateriales {
            get {
                return ResourceManager.GetString("SubMenuMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Clave.
        /// </summary>
        public static string SubMenuModificarClave {
            get {
                return ResourceManager.GetString("SubMenuModificarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Extranjera.
        /// </summary>
        public static string SubMenuMonedaExtranjera {
            get {
                return ResourceManager.GetString("SubMenuMonedaExtranjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Local.
        /// </summary>
        public static string SubMenuMonedaLocal {
            get {
                return ResourceManager.GetString("SubMenuMonedaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento de Caja.
        /// </summary>
        public static string SubMenuMovimientoDeCaja {
            get {
                return ResourceManager.GetString("SubMenuMovimientoDeCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento de Cuenta.
        /// </summary>
        public static string SubMenuMovimientoDeCuenta {
            get {
                return ResourceManager.GetString("SubMenuMovimientoDeCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento de Proveedores.
        /// </summary>
        public static string SubMenuMovimientoDeProveedores {
            get {
                return ResourceManager.GetString("SubMenuMovimientoDeProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento por Cliente.
        /// </summary>
        public static string SubMenuMovimientoPorCliente {
            get {
                return ResourceManager.GetString("SubMenuMovimientoPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento por Obra.
        /// </summary>
        public static string SubMenuMovimientoPorObra {
            get {
                return ResourceManager.GetString("SubMenuMovimientoPorObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string SubMenuNueva {
            get {
                return ResourceManager.GetString("SubMenuNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obras.
        /// </summary>
        public static string SubMenuObras {
            get {
                return ResourceManager.GetString("SubMenuObras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenes de Compra.
        /// </summary>
        public static string SubMenuOrdenesDeCompra {
            get {
                return ResourceManager.GetString("SubMenuOrdenesDeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenes de Pago.
        /// </summary>
        public static string SubMenuOrdenesDePago {
            get {
                return ResourceManager.GetString("SubMenuOrdenesDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string SubMenuPagos {
            get {
                return ResourceManager.GetString("SubMenuPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodos de Caja.
        /// </summary>
        public static string SubMenuPeriodosDeCaja {
            get {
                return ResourceManager.GetString("SubMenuPeriodosDeCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilla de Carga.
        /// </summary>
        public static string SubMenuPlanillaDeCarga {
            get {
                return ResourceManager.GetString("SubMenuPlanillaDeCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Centro de Costo.
        /// </summary>
        public static string SubMenuPorCentroDeCosto {
            get {
                return ResourceManager.GetString("SubMenuPorCentroDeCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Cuenta.
        /// </summary>
        public static string SubMenuPorCuenta {
            get {
                return ResourceManager.GetString("SubMenuPorCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Obra.
        /// </summary>
        public static string SubMenuPorObra {
            get {
                return ResourceManager.GetString("SubMenuPorObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Subcuenta.
        /// </summary>
        public static string SubMenuPorSubCuenta {
            get {
                return ResourceManager.GetString("SubMenuPorSubCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posicion Iva.
        /// </summary>
        public static string SubMenuPosicionIva {
            get {
                return ResourceManager.GetString("SubMenuPosicionIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produccion.
        /// </summary>
        public static string SubMenuProduccion {
            get {
                return ResourceManager.GetString("SubMenuProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string SubMenuProveedores {
            get {
                return ResourceManager.GetString("SubMenuProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyeccion.
        /// </summary>
        public static string SubMenuProyeccion {
            get {
                return ResourceManager.GetString("SubMenuProyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyeccion General.
        /// </summary>
        public static string SubMenuProyeccionGeneral {
            get {
                return ResourceManager.GetString("SubMenuProyeccionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyeccion por Obra.
        /// </summary>
        public static string SubMenuProyeccionPorObra {
            get {
                return ResourceManager.GetString("SubMenuProyeccionPorObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectado - Real.
        /// </summary>
        public static string SubMenuProyectado_Real {
            get {
                return ResourceManager.GetString("SubMenuProyectado-Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string SubMenuProyectos {
            get {
                return ResourceManager.GetString("SubMenuProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string SubMenuReal {
            get {
                return ResourceManager.GetString("SubMenuReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitos.
        /// </summary>
        public static string SubMenuRemitos {
            get {
                return ResourceManager.GetString("SubMenuRemitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Economico.
        /// </summary>
        public static string SubMenuReporteEconomico {
            get {
                return ResourceManager.GetString("SubMenuReporteEconomico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados por Obra.
        /// </summary>
        public static string SubMenuResultadosPorObra {
            get {
                return ResourceManager.GetString("SubMenuResultadosPorObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retenciones.
        /// </summary>
        public static string SubMenuRetenciones {
            get {
                return ResourceManager.GetString("SubMenuRetenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string SubMenuSaldo {
            get {
                return ResourceManager.GetString("SubMenuSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo de Bancos.
        /// </summary>
        public static string SubMenuSaldoDeBancos {
            get {
                return ResourceManager.GetString("SubMenuSaldoDeBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldos.
        /// </summary>
        public static string SubMenuSaldos {
            get {
                return ResourceManager.GetString("SubMenuSaldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldos de ....
        /// </summary>
        public static string SubMenuSaldosDe___ {
            get {
                return ResourceManager.GetString("SubMenuSaldosDe...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string SubMenuSalir {
            get {
                return ResourceManager.GetString("SubMenuSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situacion de Compras.
        /// </summary>
        public static string SubMenuSituacionDeCompras {
            get {
                return ResourceManager.GetString("SubMenuSituacionDeCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situacion de Obra.
        /// </summary>
        public static string SubMenuSituacionDeObra {
            get {
                return ResourceManager.GetString("SubMenuSituacionDeObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situacion de Ventas.
        /// </summary>
        public static string SubMenuSituacionDeVentas {
            get {
                return ResourceManager.GetString("SubMenuSituacionDeVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontratos.
        /// </summary>
        public static string SubMenuSubcontratos {
            get {
                return ResourceManager.GetString("SubMenuSubcontratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Cambio.
        /// </summary>
        public static string SubMenuTipoDeCambio {
            get {
                return ResourceManager.GetString("SubMenuTipoDeCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencias.
        /// </summary>
        public static string SubMenuTransferencias {
            get {
                return ResourceManager.GetString("SubMenuTransferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string SubMenuUsuarios {
            get {
                return ResourceManager.GetString("SubMenuUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        public static string SubMenuValores {
            get {
                return ResourceManager.GetString("SubMenuValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vender.
        /// </summary>
        public static string SubMenuVender {
            get {
                return ResourceManager.GetString("SubMenuVender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta de Moneda Extranjera.
        /// </summary>
        public static string SubMenuVentaDeMonedaExtranjera {
            get {
                return ResourceManager.GetString("SubMenuVentaDeMonedaExtranjera", resourceCulture);
            }
        }
    }
}
